### ISSUE TITLE
Error with rstcheck v6

### ISSUE THREAD

**Issue by ddidier** [vscode-restructuredtext/docs#11]
Hi,

I installed your extension today (a good one by the way, thanks).
I installed the `rstcheck` linter but got the following error message:

_python: No module named rstcheck.__main__; 'rstcheck' is a package and cannot be directly executed_

I gave a quick look to the `rstcheck` source code.
There is no more a `main` method in the `rstcheck` package starting at version 6 which is the latest one.
I guess this version is not yet supported by your plugin.

**Comment by lextm** [comment]
Thanks. Modified the article to indicate that rstcheck 6 is not supported.

**Comment by BobDenny** [comment]
FYI the same problem (no more `main`) affects 5.0.0. I am fairly certain that rstcheck finds problems not found by esbonio and is therefore valuable, as is doc8.  I have not gone back to < 5.0.0 but 6.0.0-post1 of rstcheck appears to be working well here. Preliminary however, needs a lot more usage to be sure.  Just put `rstcheck` as the path to rstcheck in VSCode settings and it will function.
